"""
Generates docs/Parking_Chatbot_Stage2.pptx — a presentation explaining the
RAG chatbot and human-in-the-loop administrator approval workflow. Insert
your own screenshots into the placeholder slides after generating it.

Usage:
    pip install -r docs/requirements-docs.txt
    python -m docs.generate_presentation
"""
from pptx import Presentation
from pptx.util import Inches, Pt

OUTPUT_PATH = "docs/Parking_Chatbot_Stage2.pptx"


def _add_title_slide(prs, title, subtitle):
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle


def _add_bullet_slide(prs, title, bullets):
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    body = slide.placeholders[1].text_frame
    body.clear()
    for i, bullet in enumerate(bullets):
        p = body.paragraphs[0] if i == 0 else body.add_paragraph()
        p.text = bullet
        p.font.size = Pt(18)


def _add_screenshot_placeholder_slide(prs, title, note):
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = title
    box = slide.shapes.add_textbox(Inches(1), Inches(1.5), Inches(8), Inches(4))
    box.text_frame.text = f"[Insert screenshot here]\n\n{note}"


def build():
    prs = Presentation()

    _add_title_slide(prs, "Parking Reservation Chatbot — Stage 2",
                      "RAG assistant with human-in-the-loop reservation approval")

    _add_bullet_slide(prs, "Problem & Scope", [
        "Chatbot answers parking questions: info, hours, prices, availability, location",
        "Collects reservation details and escalates complete requests to an administrator",
        "Administrator can approve or refuse; the user can ask the bot for the decision",
        "Protect personal information and measure retrieval and answer quality",
    ])

    _add_bullet_slide(prs, "Architecture Overview", [
        "PDFs -> PyPDFLoader -> merged full-document text",
        "SemanticChunker: meaning-based chunking (embedding distance between sentences)",
        "Chunks + document metadata persisted in SQLite (source of truth)",
        "Chunks embedded into vector DB (Milvus, auto-fallback to Chroma)",
        "Dynamic data (hours/prices/availability) served from a separate SQL table",
        "AdminAgent and chatbot coordinate request state through a shared SQLite store",
    ])

    _add_bullet_slide(prs, "RAG & Conversation Flow", [
        "Intent classifier routes each message: static_info / dynamic_info / reservation / other",
        "static_info -> vector similarity search -> grounded LLM answer",
        "dynamic_info -> SQL lookup -> grounded LLM answer",
        "reservation -> collect name, car number, period, and optional parking lot",
        "completed details -> create pending request, notify admin, return request id",
        "status_check -> read admin decision from shared request store and reply to user",
    ])

    _add_bullet_slide(prs, "Stage 2 — Administrator Agent", [
        "LangChain tool-calling agent helps the administrator manage reservations",
        "Tools list pending requests, approve, refuse with a reason, and check status",
        "Request records store details, status, decision reason, and timestamps in SQLite",
        "A unique request id connects the user conversation to the administrator decision",
    ])

    _add_bullet_slide(prs, "Escalation & Communication", [
        "Chatbot creates the request only after reservation slot-filling is complete",
        "AdminAgent composes a concise request summary and dispatches a notification",
        "Channels: console, SMTP email, Slack webhook, or external REST endpoint",
        "Notification alerts the admin; approval/refusal is recorded via the CLI or Admin API",
        "Both agents read and update the same configurable SQLite request database",
    ])

    _add_bullet_slide(prs, "Administrator Decision Interfaces", [
        "Natural-language CLI: 'list pending requests', 'approve request <id>', or refuse with a reason",
        "FastAPI endpoints create, list, retrieve, and decide reservation requests",
        "Optional ADMIN_API_KEY protects API write operations with the x-api-key header",
        "The chatbot reads pending/approved/refused status and relays the decision to the user",
    ])

    _add_bullet_slide(prs, "Guardrails (PII Protection)", [
        "Presidio-based PII detection/redaction (falls back to regex if unavailable)",
        "Inbound: blocks credit card / SSN / IBAN pasted outside the reservation flow",
        "Outbound: redacts any PII that leaks into RAG-generated answers",
        "Reservation summary (user's own data) is exempt from outbound redaction by design",
    ])

    _add_bullet_slide(prs, "Evaluation Methodology", [
        "Test questions auto-generated by an LLM directly from ingested PDF chunks",
        "Each question has a ground-truth chunk id and reference answer",
        "Retrieval: Recall@K and Precision@K against ground-truth chunk ids",
        "Answer correctness: LLM-as-judge (or embedding similarity) vs reference answer",
        "Latency: retrieval and end-to-end timing, reported as mean/P50/P95",
    ])

    _add_screenshot_placeholder_slide(prs, "Demo — Answering a Static Info Question",
        "Chat screenshot: 'Where is the airport parking located?' and the bot's grounded answer.")
    _add_screenshot_placeholder_slide(prs, "Demo — Reservation Flow",
        "Chat screenshot: bot collecting name, surname, car number, and reservation period.")
    _add_screenshot_placeholder_slide(prs, "Demo — Admin Approval Handoff",
        "Show the chatbot's request id and the matching pending request in the admin CLI/API or notification.")
    _add_screenshot_placeholder_slide(prs, "Demo — Decision Returned to User",
        "Show the administrator approving or refusing a request, then the chatbot reporting its status and reason.")
    _add_screenshot_placeholder_slide(prs, "Demo — Guardrail Blocking Sensitive Input",
        "Screenshot: bot refusing a message with a pasted credit card number.")
    _add_screenshot_placeholder_slide(prs, "Evaluation Report",
        "Screenshot of evaluation/REPORT.md: Recall@K, Precision@K, accuracy, latency.")

    _add_bullet_slide(prs, "Testing & CI/CD", [
        "pytest unit tests across every module (2+ tests each), fully offline via fakes",
        "GitHub Actions CI: lint + test + docker build on every push/PR",
        "Terraform (kreuzwerker/docker provider) to provision Milvus + app as code",
    ])

    _add_bullet_slide(prs, "Current Stage & Next Steps", [
        "Stage 2 delivered: chatbot-to-admin escalation, notifications, decisions, and user status checks",
        "Stage 3: MCP server / tool call to record approved reservations to file",
        "Stage 4: LangGraph orchestration end-to-end, load + integration tests, docs",
    ])

    prs.save(OUTPUT_PATH)
    print(f"Saved presentation to {OUTPUT_PATH}")


if __name__ == "__main__":
    build()